version: "3.9"
services:
  server:
    build: ./
    ports:
      - '3200:3200'
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: kells
      POSTGRES_PASSWORD: '1234'
      POSTGRES_DB: nodewayfarer
    volumes:
      - data:/var/lib/potgresql/data
    ports:
      - "5432:5432"

volumes:
  data:


