name: Continuous Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
  workflow_dispatch: # Trigger on pushes to the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: nodewayfarer_test
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install

      - name: Run database migrations
        run: DB_URL=postgres://postgres:postgres@localhost:5432/nodewayfarer_test npm run migrate up
      - name: Run tests
        run: npm test
