name: Continuous Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
  workflow_dispatch: # Trigger on pushes to the main branch

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci

      - name: Run database migrations
        run: npm run migrate up
        env:
          # The hostname used to communicate with the PostgreSQL service container
          DB_URL: postgres://postgres:postgres@localhost:5432/postgres
          # The default PostgreSQL port

      - name: Run tests
        run: npm test
